### ISSUE TITLE
Is there time service inside enclave?

### ISSUE THREAD

**Issue by raindust** [aws/aws-nitro-enclaves-nsm-api#15]
There are time services such as [Amazon Time Sync Service](https://aws.amazon.com/cn/blogs/mt/manage-amazon-ec2-instance-clock-accuracy-using-amazon-time-sync-service-and-amazon-cloudwatch-part-1/) outside the enclave, however, they should pass from parent instance client and we can't approve the time is not modified from outside.
So is there any way I can get time from enclave? I can only find get attestation documents and random API [here](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/nsm-lib/src/lib.rs).

**Comment by petreeftime** [comment]
The time is automatically sync'ed via the KVM clock, there is no need to provide this via an external service. Did you detect any meaningful clock difference within the enclave?
