### ISSUE TITLE
Timestamps in AttestationDocs are incorrect

### ISSUE THREAD

**Issue by exFalso** [aws/aws-nitro-enclaves-nsm-api#20]
The code clearly states that the timestamp should be seconds since epoch:

https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/9ddb589875baf345d085a980aa96cf3a4e480ea8/nsm-io/src/lib.rs#L219-L220

However, in actual attestations we are seeing **milliseconds** since epoch being reported.

**Comment by petreeftime** [comment]
Milliseconds is correct, the docs need to be updated.

**Comment by petreeftime** [comment]
Fixed in #21
