### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by paholg** [aws/aws-nitro-enclaves-nsm-api#22]
I am using nsm-driver and nsm-io in a Rust application, and it would be helpful to have those published on crates.io. As is, I will likely have to vendor them.

**Comment by petreeftime** [comment]
It's been published here: https://crates.io/crates/aws-nitro-enclaves-nsm-api

**Comment by paholg** [comment]
Awesome, thank you!

**Comment by vidhatha-ob** [comment]
> It's been published here: https://crates.io/crates/aws-nitro-enclaves-nsm-api

great! thank you!
