### ISSUE TITLE
Request attestation document inside vsock-sample.py

### ISSUE THREAD

**Issue by Jonas-Metzger** [aws/aws-nitro-enclaves-nsm-api#9]
Hi @petreeftime and other contributors!

You have this neat sample showing how to communicate with the enclave ("server") from the EC2 instance ("client"), in python:

https://github.com/aws/aws-nitro-enclaves-samples/blob/main/vsock_sample/py/vsock-sample.py

I'm wondering how to get the enclave/server side of the code to request the attestation document (to then share it with the client). Is there a CLI command that would obtain it from the Nitro Hypervisor? Otherwise, I assume I'd have to use a  [python-rust bindings utility like pyo3](https://github.com/PyO3/pyo3). Which is the right rust function to point it to?

Am I correct in assuming that I will be able to include arbitrary data (in particular: a public key manually generated by the python code running inside the enclave) into the attestation document by including it in the attestation request call?

Thanks a lot!

**Comment by petreeftime** [comment]
Also answering for: https://github.com/aws/aws-nitro-enclaves-sdk-c/issues/57.

We don't currently have a python API for this, specifically, although pyo3 could be a neat solution to it, but we haven't looked into it so far.

In broad, to get an [Attestation Document](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/nsm-io/src/lib.rs#L82) containing any form of user data, the user needs to create a request for it:
```
fn main() {
    let nsm_fd = nsm_driver::nsm_init();

    let public_key = serde_bytes::ByteBuf::from("my super secret key");
    let hello = serde_bytes::ByteBuf::from("hello, world!");

    let request = nsm_io::Request::Attestation {
        public_key: Some(public_key),
        user_data: Some(hello),
        nonce: None,
    };

    let response = nsm_driver::nsm_process_request(nsm_fd, request);
    println!("{:?}", response);

    nsm_driver::nsm_exit(nsm_fd);
}
```

Another solution for python, but less elegant, would be create an executable that python can call using the already available libraries.

**Comment by Jonas-Metzger** [comment]
Thanks a lot! Sorry for spamming, I wasn't sure about the right place to ask.

I'm not familiar with Rust at all, so I'll try to code up a pyo3 solution. I hope you'll bear with me while I figure out what to do. The readme at 

https://github.com/aws/aws-nitro-enclaves-samples/tree/main/vsock_sample/py

describes a specific docker setup process for the enclave that suffices to run the vsock example. Let's say I want to get a minimal .rs example of your `fn main()` above, are there any `use` statements I need to put at the top of the file? Do I need to explicitly install `aws-nitro-enclaves-nsm-api` somehow, or maybe `nsm_driver` `serde_bytes` and `nsm_io` manually?

**Comment by petreeftime** [comment]
The enclave itself doesn't  provide any software, and all the software comes from the person building the enclave, via the build-enclave command. The default tooling provides a Linux kernel, and init process + parameters for it and whatever the user specifies as the Docker image to use, so in this case all the user software comes from that Docker image.

With regards to how one would build the Rust code, I'll look to adding a sample to the samples repo, but in short: you first need to declare the dependency in the `Cargo.toml` file of the project:
```
[dependencies]
serde_bytes = "0.11"

[dependencies.nsm-driver]
git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git"
rev = "4f468c4"

[dependencies.nsm-io]
git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git"
rev = "4f468c4"
```

The use inside the files just helps with keeping the lines short, and doesn't have an impact on usage otherwise. For example, the code above can be "compressed" to: 
```
use nsm_io::Request;
use serde_bytes::ByteBuf;

fn main() {
    let nsm_fd = nsm_driver::nsm_init();

    let public_key = ByteBuf::from("my super secret key");
    let hello = ByteBuf::from("hello, world!");

    let request = Request::Attestation {
        public_key: Some(public_key),
        user_data: Some(hello),
        nonce: None,
    };

    let response = nsm_driver::nsm_process_request(nsm_fd, request);
    println!("{:?}", response);

    nsm_driver::nsm_exit(nsm_fd);
}
```

The other important aspect here is the docker file. I will come back with an example that builds both a Rust binary and includes it in a Docker container container with Python.

**Comment by Jonas-Metzger** [comment]
Thank you very much for the clarification and the little Rust 101 @petreeftime ! I think I'm beginning to understand what's going on. A minimal docker example that builds such a Rust binary and contains client-server communication in python similar to the [vsock-sample ](https://github.com/aws/aws-nitro-enclaves-samples/blob/main/vsock_sample/py/vsock-sample.py) would be awesome. Should then be straightforward to call this binary from python's `subprocess` (no `pyo3` or `runner ` needed), right?

Thank you so much for taking the time to do this! That will be way more efficient than me trying to get these basics to work via trial and error. Keep me posted!

**Comment by Jonas-Metzger** [comment]
Hi @petreeftime , I'd love to start building off your docker container. But I'm sure you've got a lot on your plate. Is there any way I can help accelerate the process?

**Comment by Jonas-Metzger** [comment]
Hi @petreeftime , I'd love to start building off the docker container example you offered to build. What's your guess for when you'll be able to share it? 

I'm having trouble understanding how I would have to set up the container to get it to build a working rust executable inside the `.eif`

**Comment by dblanzeanu** [comment]
Hi @Jonas-Metzger, please check the open PR which implements what @petreeftime suggested above.
The PR is still work in progress, however this should get you started.

**Comment by Jonas-Metzger** [comment]
Thank you so much for your efforts! I'll try it out asap!

**Comment by Jonas-Metzger** [comment]
Thank you again @dblanzeanu  and @petreeftime , the att-doc-retriever-sample works for me now, and I was able to play around and modify the python and rust code a bit. 

Currently, the document is a list of integers. How do I decode it into something that looks like the example in [attestation_process.md](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/docs/attestation_process.md):


```
AttestationDocument = {
    module_id: text,               ; issuing Nitro hypervisor module ID
    timestamp: uint .size 8,       ; UTC time when document was created, in
                                   ; milliseconds since UNIX epoch
    digest: digest,                ; the digest function used for calculating the
                                   ; register values
    pcrs: { + index => pcr },      ; map of all locked PCRs at the moment the
                                   ; attestation document was generated
    certificate: cert,             ; the infrastucture certificate used to sign this
                                   ; document, DER encoded
    cabundle: [* cert],            ; issuing CA bundle for infrastructure certificate
    ? public_key: user_data,       ; an optional DER-encoded key the attestation
                                   ; consumer can use to encrypt data with
    ? user_data: user_data,        ; additional signed user data, defined by protocol
    ? nonce: user_data,            ; an optional cryptographic nonce provided by the
                                   ; aattestation consumer as a proof of authenticity
}

cert = bytes .size (1..1024)       ; DER encoded certificate
user_data = bytes .size (0..1024)
pcr = bytes .size (32/48/64)       ; PCR content
index = 0..31
digest = "SHA384"
```

I assume the list of integers is the "signed attestation document in CBOR format" at the beginning of the flowchart below: 
https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/docs/figures/attestation_document_validation_flow.png
Is there any example code doing the remaining steps in the flowchart that you could share with me?

Also, it seems to me that right now, the attestation document is sent through the vsock channel in multiple chunks. Is that because println! does some line breaks or does the vsock python code chunk it up? Can't the rust code just save the attestation document to a file, which we could open from python?

Thanks a lot for your support!

**Comment by Jonas-Metzger** [comment]
Found a solution here: https://stackoverflow.com/a/17668009.

Everything works now. Thanks!
